# Generated by Django 3.2.13 on 2023-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mbti', models.CharField(max_length=4)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
