# Generated by Django 3.2.13 on 2023-02-02 19:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230201_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawlers',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
