# Generated by Django 3.2.13 on 2023-02-03 18:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_brawlers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawlers',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
